const DEFAULT_STATE = {
  apiKey: '',
  capital: { cash: 0, invested: 0, reserve: 0 },
  target: 50000,
  monthlySavings: 800,
  rules: { maxPortfolioLossPct: 0.15, marketBuyMoreDrawdown: 0.20, marketRiskOffDrawdown: 0.30, profitTrimPct: 0.40, stopLossPct: 0.30, trendReviewPct: 0.12, monthlySafe: 700, monthlyRisk: 100 },
  tiers: {
    CORE: { maxPosPct: 0.45, maxTierPct: 0.60, dip1: 0.20, dip2: 0.30, dip3: 0.40, buy: 250 },
    QUALITY: { maxPosPct: 0.10, maxTierPct: 0.20, dip1: 0.20, dip2: 0.30, dip3: 0.40, buy: 100 },
    THEME: { maxPosPct: 0.06, maxTierPct: 0.20, dip1: 0.30, dip2: 0.45, dip3: 0.60, buy: 75 },
    SPEC: { maxPosPct: 0.04, maxTierPct: 0.15, dip1: 0.50, dip2: 0.60, dip3: 0.70, buy: 50 }
  },
  holdings: [],
  expanded: {}
};
const clone=o=>JSON.parse(JSON.stringify(o));
let state=loadState();
function safeNum(n){const x=Number(n);return Number.isFinite(x)?x:0;}
function mergeDefaults(d,s){const m=clone(d);if(!s||typeof s!=='object')return m;return {...m,...s,capital:{...m.capital,...(s.capital||{})},rules:{...m.rules,...(s.rules||{})},tiers:{...m.tiers,...(s.tiers||{})},holdings:Array.isArray(s.holdings)?s.holdings:[],expanded:s.expanded||{}};}
function loadState(){try{return mergeDefaults(DEFAULT_STATE,JSON.parse(localStorage.getItem('driftBudgetState')||localStorage.getItem('houseFundState')||'{}'));}catch{return clone(DEFAULT_STATE);}}
function saveState(){localStorage.setItem('driftBudgetState',JSON.stringify(state));}
const money=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const money2=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const pct=n=>`${(Number(n||0)*100).toFixed(0)}%`; const pct1=n=>`${(Number(n||0)*100).toFixed(1)}%`;
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function calc(){const stockValue=state.holdings.reduce((s,h)=>s+safeNum(h.shares)*safeNum(h.price),0);const portfolio=safeNum(state.capital.cash)+safeNum(state.capital.invested)+safeNum(state.capital.reserve)+stockValue;const riskAssets=safeNum(state.capital.invested)+stockValue;const riskPct=portfolio?riskAssets/portfolio:0;const lossBudget=portfolio*safeNum(state.rules.maxPortfolioLossPct);const estimatedLossRisk=stockValue*.5;const marketDrawdownProxy=weightedMarketDrawdown();let regime='NORMAL';if(marketDrawdownProxy>=state.rules.marketRiskOffDrawdown)regime='RISK-OFF';else if(marketDrawdownProxy>=state.rules.marketBuyMoreDrawdown)regime='SELECTIVE';let glide='ACCUMULATE';if(portfolio>=state.target)glide='TARGET MET';else if(portfolio>=state.target*.9)glide='PROTECT';else if(portfolio>=state.target*.8)glide='SLOW RISK';const holdings=state.holdings.map(h=>enrichHolding(h,portfolio,regime,estimatedLossRisk,lossBudget));return{portfolio,stockValue,riskAssets,riskPct,lossBudget,estimatedLossRisk,marketDrawdownProxy,regime,glide,holdings};}
function weightedMarketDrawdown(){const q=state.holdings.filter(h=>['CORE','QUALITY'].includes(h.tier)&&h.high52);if(!q.length)return 0;return q.reduce((s,h)=>s+Math.max(0,1-h.price/h.high52),0)/q.length;}
function enrichHolding(h,total,regime,estimatedLossRisk,lossBudget){const tier=state.tiers[h.tier]||state.tiers.SPEC;const value=safeNum(h.shares)*safeNum(h.price);const posPct=total?value/total:0;const maxValue=total*safeNum(tier.maxPosPct);const draw52=h.high52?Math.max(0,1-h.price/h.high52):0;const shortDraw=h.shortHigh?Math.max(0,1-h.price/h.shortHigh):0;const profit=h.costBasis?(h.price-h.costBasis)/h.costBasis:0;const blocked=regime==='RISK-OFF'||estimatedLossRisk>lossBudget||value>maxValue;const buy=blocked?0:draw52>=tier.dip3?tier.buy*3:draw52>=tier.dip2?tier.buy*2:draw52>=tier.dip1?tier.buy:0;const sell=[];if(value>maxValue)sell.push('TRIM');if(h.costBasis&&profit<=-state.rules.stopLossPct)sell.push('STOP');if(h.costBasis&&profit>=state.rules.profitTrimPct)sell.push('PROFIT');if(shortDraw>=state.rules.trendReviewPct)sell.push('TREND');const action=sell[0]||(buy>0?'BUY':'HOLD');return{...h,value,posPct,maxValue,draw52,shortDraw,profit,buy,sell,action};}
async function fetchDaily(symbol,apiKey){const url=`https://api.twelvedata.com/time_series?symbol=${encodeURIComponent(symbol)}&interval=1day&outputsize=370&apikey=${encodeURIComponent(apiKey)}`;const res=await fetch(url);if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(data.status==='error')throw new Error(data.message||'Twelve Data error');if(!Array.isArray(data.values)||!data.values.length)throw new Error('No daily data');const values=data.values.filter(v=>Number.isFinite(Number(v.close))).sort((a,b)=>new Date(b.datetime)-new Date(a.datetime));const latest=values[0];const highs=values.map(v=>safeNum(v.high||v.close)).filter(Boolean);const short=values.slice(0,30).reverse().map(v=>safeNum(v.close));return{price:safeNum(latest.close),high52:Math.max(...highs),shortHigh:Math.max(...short),spark:short,lastUpdated:latest.datetime};}
async function refreshPrices(){const status=document.getElementById('apiStatus');const apiKey=(document.getElementById('apiKeyInput')?.value||state.apiKey||'').trim();if(!apiKey){if(status)status.textContent='Paste API key first.';return;}state.apiKey=apiKey;saveState();const errors=[];for(let i=0;i<state.holdings.length;i++){const h=state.holdings[i];if(status)status.textContent=`Refreshing ${h.ticker} (${i+1}/${state.holdings.length})…`;try{state.holdings[i]={...h,...await fetchDaily(h.apiSymbol||h.ticker,apiKey)};saveState();}catch(e){errors.push(`${h.ticker}: ${e.message}`);}await sleep(850);}if(status)status.textContent=errors.length?errors.join(' | '):`Updated ${new Date().toLocaleTimeString()}`;render();}
function sparkline(vals,trend='up'){if(!vals||vals.length<2)return'<svg class="spark" viewBox="0 0 120 44"></svg>';const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const pts=vals.map((v,i)=>`${i*(120/(vals.length-1))},${42-((v-min)/range)*36}`).join(' ');return`<svg class="spark ${trend}" viewBox="0 0 120 44" preserveAspectRatio="none"><polyline points="${pts}"/></svg>`;}
function actionClass(a){return a==='BUY'?'buy':a==='TRIM'||a==='PROFIT'?'trim':a==='STOP'?'stop':'hold';}
function render(){const c=calc();document.getElementById('totalFund').textContent=money(c.portfolio);document.getElementById('riskAssetsValue').textContent=money(c.riskAssets);document.getElementById('riskPct').textContent=pct1(c.riskPct);document.getElementById('targetValue').textContent=money(state.target);document.getElementById('lossBudget').textContent=money(c.lossBudget);document.getElementById('progressBar').style.width=`${Math.min(100,c.portfolio/state.target*100)}%`;const months=state.monthlySavings>0?Math.max(0,Math.ceil((state.target-c.portfolio)/state.monthlySavings)):0;document.getElementById('targetDate').textContent=`${months} mo to target`;document.getElementById('marketRegime').textContent=c.regime;document.getElementById('marketMode').textContent=c.glide;document.getElementById('marketRegimeNote').textContent=`Market proxy drawdown ${pct1(c.marketDrawdownProxy)}`;document.getElementById('riskStatus').textContent=c.estimatedLossRisk>c.lossBudget?'RISK HIGH':'GOOD';document.getElementById('riskNote').textContent=`Loss at risk ${money(c.estimatedLossRisk)} of ${money(c.lossBudget)} budget`;document.getElementById('monthlyRouting').textContent=c.regime==='RISK-OFF'?'Safer assets only':`${money(state.rules.monthlySafe)} safe / ${money(state.rules.monthlyRisk)} risk`;renderHoldings(c.holdings);renderSignals(c.holdings,c);renderInputs();renderRules();}
function renderHoldings(holdings){const el=document.getElementById('holdingsList');el.innerHTML=holdings.length?holdings.map((h,i)=>{const expanded=!!state.expanded[h.ticker];const trend=h.spark&&h.spark[h.spark.length-1]>=h.spark[0]?'up':'down';return`<article class="holdingCard ${expanded?'expanded':''}"><button class="cardToggle" data-toggle="${h.ticker}"><div class="tickerBlock"><div class="logoBubble">${h.ticker.slice(0,1)}</div><div><h3>${h.ticker}</h3><span class="tier ${h.tier}">${h.tier}</span></div></div><div class="priceBlock"><span>Price</span><strong>${money2(h.price)}</strong><small class="${h.profit>=0?'green':'red'}">${pct1(h.profit)}</small></div><div class="sparkBlock"><span>30D</span>${sparkline(h.spark,trend)}</div><div class="actionBlock"><span>Action</span><b class="action ${actionClass(h.action)}">${h.action}</b></div><span class="chev">${expanded?'⌄':'›'}</span></button>${expanded?`<div class="detailGrid"><div><span>Shares</span><strong>${h.shares}</strong></div><div><span>Cost Basis</span><strong>${money2(h.costBasis)}</strong></div><div><span>Market Value</span><strong>${money(h.value)}</strong></div><div><span>Position</span><strong>${pct1(h.posPct)}</strong></div><div><span>52W High</span><strong>${money2(h.high52)}</strong></div><div><span>52W Drawdown</span><strong class="red">${pct1(h.draw52)}</strong></div><div><span>30D Drawdown</span><strong class="red">${pct1(h.shortDraw)}</strong></div><div><span>Max Position</span><strong>${money(h.maxValue)}</strong></div><button class="danger" data-remove="${i}">Remove</button></div>`:''}</article>`}).join(''):'<article class="emptyCard">No holdings yet. Tap + Add Holding.</article>';}
function alertHtml(items,empty='None'){return items.length?items.map(x=>`<div class="alert">${x}</div>`).join(''):`<p class="muted">${empty}</p>`;}
function renderSignals(holdings,c){const buys=holdings.filter(h=>h.buy>0).map(h=>`${h.ticker}: buy up to ${money(h.buy)} (${pct1(h.draw52)} 52W dip)`);const sells=holdings.filter(h=>h.sell.length).map(h=>`${h.ticker}: ${h.sell.join(' + ')}`);const top=[];if(c.estimatedLossRisk>c.lossBudget)top.push('Loss budget exceeded: pause new risk.');if(c.riskPct>.65)top.push('Risk assets are high relative to target capital.');top.push(...sells.slice(0,3),...buys.slice(0,3));document.getElementById('buySignals').innerHTML=alertHtml(buys);document.getElementById('sellSignals').innerHTML=alertHtml(sells);document.getElementById('topAlerts').innerHTML=alertHtml(top);}
function renderInputs(){document.getElementById('apiSettings').innerHTML=`<label>API Key<input id="apiKeyInput" type="password" value="${state.apiKey||''}" autocomplete="off"></label><p id="apiStatus" class="muted">Stored locally on this device only.</p>`;document.getElementById('portfolioSettings').innerHTML=`<label>Target Amount<input data-key="target" type="number" step="any" value="${state.target}"></label><label>Monthly Savings<input data-key="monthlySavings" type="number" step="any" value="${state.monthlySavings}"></label><label>Safe / Cash Capital<input data-key="capital:cash" type="number" step="any" value="${state.capital.cash}"></label><label>Invested Capital Outside Holdings<input data-key="capital:invested" type="number" step="any" value="${state.capital.invested}"></label><label>Reserve Capital<input data-key="capital:reserve" type="number" step="any" value="${state.capital.reserve}"></label>`;}
function renderRules(){document.getElementById('ruleInputs').innerHTML=Object.entries(state.rules).map(([k,v])=>`<label>${k}<input data-key="rule:${k}" type="number" step="any" value="${v}"></label>`).join('');}
function addHolding(){const ticker=(document.getElementById('newTicker')?.value||'').trim().toUpperCase();const shares=safeNum(document.getElementById('newShares')?.value);const costBasis=safeNum(document.getElementById('newCostBasis')?.value);const tier=document.getElementById('newTier')?.value||'SPEC';if(!ticker||shares<=0)return;state.holdings.push({ticker,apiSymbol:ticker,tier,shares,costBasis,price:0,high52:0,shortHigh:0,spark:[],lastUpdated:'Refresh needed'});state.expanded[ticker]=true;saveState();closeModal();render();}
function openModal(){document.getElementById('addModal').classList.remove('hidden');}
function closeModal(){document.getElementById('addModal').classList.add('hidden');['newTicker','newShares','newCostBasis'].forEach(id=>{const x=document.getElementById(id);if(x)x.value='';});}
function applyField(el){const key=el.dataset.key;if(!key)return;if(key==='target')state.target=safeNum(el.value);else if(key==='monthlySavings')state.monthlySavings=safeNum(el.value);else if(key.startsWith('capital:'))state.capital[key.split(':')[1]]=safeNum(el.value);else if(key.startsWith('rule:'))state.rules[key.split(':')[1]]=safeNum(el.value);saveState();render();}
document.addEventListener('change',e=>applyField(e.target));document.addEventListener('click',e=>{if(e.target.closest('[data-toggle]')){const t=e.target.closest('[data-toggle]').dataset.toggle;state.expanded[t]=!state.expanded[t];saveState();render();}if(e.target.id==='openAddHoldingBtn')openModal();if(e.target.id==='closeModalBtn')closeModal();if(e.target.id==='addHoldingBtn')addHolding();if(e.target.id==='refreshPricesBtn')refreshPrices();if(e.target.dataset.remove){state.holdings.splice(Number(e.target.dataset.remove),1);saveState();render();}if(e.target.id==='editTargetBtn')document.querySelector('[data-tab="inputs"]').click();});
document.querySelectorAll('.tab').forEach(btn=>{btn.onclick=()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tabPanel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab).classList.add('active');};});
document.getElementById('resetBtn').onclick=()=>{localStorage.removeItem('houseFundState');localStorage.removeItem('driftBudgetState');state=clone(DEFAULT_STATE);render();};
document.getElementById('exportBtn').onclick=()=>{document.getElementById('backupBox').value=JSON.stringify(state,null,2);};
render();
